### ISSUE TITLE
Any performance numbers?

### ISSUE THREAD

**Issue by pgplus1628** [alibaba/euler#2]
Great work!
It would be great if some performance numbers(for Node2Vec and LINE) are provided.

**Comment by pgplus1628** [comment]
@renyi533 
Thanks for your reply. Here I mean "training QPS".
Looking forward to seeing some training numbers on billion or trillion edges of graphs!

**Comment by pgplus1628** [comment]
@renyi533 To the best of my knowledge, it seems that Euler assumes the embeddings of all vertices can be held in the CPU memory (https://github.com/alibaba/euler/blob/c45225119c5b991ca953174f06c2f223562f34c9/tf_euler/python/layers.py#L131).

For large graphs, the embeddings may exceed the CPU memory limit.
Is there any way to make Euler be able to handle this case?

**Comment by renyi533** [comment]
@pgplus1628 @yangsiran  Please refer to https://stackoverflow.com/questions/47170879/what-is-partitioner-parameter-in-tensorflow-variable-scope-used-for.

You can define variable partition per variable with tf.get_variable. But this will pass the count of partitions to each inner object, which is not so elegant. That's why we do not use this way.

Instead, you can define default partitioner with tf.variable_scope. So we recommend you to use default partitioner in your main script and place "layer" under it. 

Our ppi_main/reddit_main is a simple example. We can write a better example for illustration.

**Comment by renyi533** [comment]
@pgplus1628 https://github.com/alibaba/euler/wiki/性能测试。这里添加了性能测试结果。
